import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const verses = [
'وَالنَّجْمِ إِذَا هَوَىٰ','مَا ضَلَّ صَاحِبُكُمْ وَمَا غَوَىٰ','وَمَا يَنطِقُ عَنِ الْهَوَىٰ','إِنْ هُوَ إِلَّا وَحْيٌ يُوحَىٰ','عَلَّمَهُ شَدِيدُ الْقُوَىٰ','ذُو مِرَّةٍ فَاسْتَوَىٰ','وَهُوَ بِالْأُفُقِ الْأَعْلَىٰ','ثُمَّ دَنَا فَتَدَلَّىٰ','فَكَانَ قَابَ قَوْسَيْنِ أَوْ أَدْنَىٰ',
'فَأَوْحَىٰ إِلَىٰ عَبْدِهِ مَا أَوْحَىٰ','مَا كَذَبَ الْفُؤَادُ مَا رَأَىٰ','أَفَتُمَارُونَهُ عَلَىٰ مَا يَرَىٰ','وَلَقَدْ رَآهُ نَزْلَةً أُخْرَىٰ','عِندَ سِدْرَةِ الْمُنتَهَىٰ','عِندَهَا جَنَّةُ الْمَأْوَىٰ','إِذْ يَغْشَى السِّدْرَةَ مَا يَغْشَىٰ','مَا زَاغَ الْبَصَرُ وَمَا طَغَىٰ','لَقَدْ رَأَىٰ مِنْ آيَاتِ رَبِّهِ الْكُبْرَىٰ',
'أَفَرَأَيْتُمُ اللَّاتَ وَالْعُزَّىٰ','وَمَنَاةَ الثَّالِثَةَ الْأُخْرَىٰ','أَلَكُمُ الذَّكَرُ وَلَهُ الْأُنثَىٰ','تِلْكَ إِذًا قِسْمَةٌ ضِيزَىٰ','إِنْ هِيَ إِلَّا أَسْمَاءٌ سَمَّيْتُمُوهَا أَنتُمْ وَآبَاؤُكُم مَّا أَنزَلَ اللَّهُ بِهَا مِن سُلْطَانٍ إِن يَتَّبِعُونَ إِلَّا الظَّنَّ وَمَا تَهْوَى الْأَنفُسُ وَلَقَدْ جَاءَهُم مِّن رَّبِّهِمُ الْهُدَىٰ','أَمْ لِلْإِنسَانِ مَا تَمَنَّىٰ','فَلِلَّهِ الْآخِرَةُ وَالْأُولَىٰ','وَكَم مِّن مَّلَكٍ فِي السَّمَاوَاتِ لَا تُغْنِي شَفَاعَتُهُمْ شَيْئًا إِلَّا مِن بَعْدِ أَن يَأْذَنَ اللَّهُ لِمَن يَشَاءُ وَيَرْضَىٰ','إِنَّ الَّذِينَ لَا يُؤْمِنُونَ بِالْآخِرَةِ لَيُسَمُّونَ الْمَلَائِكَةَ تَسْمِيَةَ الْأُنثَىٰ','وَمَا لَهُم بِهِ مِنْ عِلْمٍ إِن يَتَّبِعُونَ إِلَّا الظَّنَّ وَإِنَّ الظَّنَّ لَا يُغْنِي مِنَ الْحَقِّ شَيْئًا','فَأَعْرِضْ عَن مَّن تَوَلَّىٰ عَن ذِكْرِنَا وَلَمْ يُرِدْ إِلَّا الْحَيَاةَ الدُّنْيَا','ذَٰلِكَ مَبْلَغُهُم مِّنَ الْعِلْمِ إِنَّ رَبَّكَ هُوَ أَعْلَمُ بِمَن ضَلَّ عَن سَبِيلِهِ وَهُوَ أَعْلَمُ بِمَنِ اهْتَدَىٰ',
'وَلِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ لِيَجْزِيَ الَّذِينَ أَسَاءُوا بِمَا عَمِلُوا وَيَجْزِيَ الَّذِينَ أَحْسَنُوا بِالْحُسْنَى','الَّذِينَ يَجْتَنِبُونَ كَبَائِرَ الْإِثْمِ وَالْفَوَاحِشَ إِلَّا اللَّمَمَ إِنَّ رَبَّكَ وَاسِعُ الْمَغْفِرَةِ هُوَ أَعْلَمُ بِكُمْ إِذْ أَنشَأَكُم مِّنَ الْأَرْضِ وَإِذْ أَنتُمْ أَجِنَّةٌ فِي بُطُونِ أُمَّهَاتِكُمْ فَلَا تُزَكُّوا أَنفُسَكُمْ هُوَ أَعْلَمُ بِمَنِ اتَّقَىٰ','أَفَرَأَيْتَ الَّذِي تَوَلَّىٰ','وَأَعْطَىٰ قَلِيلًا وَأَكْدَىٰ','أَعِندَهُ عِلْمُ الْغَيْبِ فَهُوَ يَرَىٰ','أَمْ لَمْ يُنَبَّأْ بِمَا فِي صُحُفِ مُوسَىٰ','وَإِبْرَاهِيمَ الَّذِي وَفَّىٰ','أَلَّا تَزِرُ وَازِرَةٌ وِزْرَ أُخْرَىٰ','وَأَن لَّيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَىٰ','وَأَنَّ سَعْيَهُ سَوْفَ يُرَىٰ',
'ثُمَّ يُجْزَاهُ الْجَزَاءَ الْأَوْفَىٰ','وَأَنَّ إِلَىٰ رَبِّكَ الْمُنتَهَىٰ','وَأَنَّهُ هُوَ أَضْحَكَ وَأَبْكَىٰ','وَأَنَّهُ هُوَ أَمَاتَ وَأَحْيَا','وَأَنَّهُ خَلَقَ الزَّوْجَيْنِ الذَّكَرَ وَالْأُنثَىٰ','مِن نُّطْفَةٍ إِذَا تُمْنَىٰ','وَأَنَّ عَلَيْهِ النَّشْأَةَ الْأُخْرَىٰ','وَأَنَّهُ هُوَ أَغْنَىٰ وَأَقْنَىٰ','وَأَنَّهُ هُوَ رَبُّ الشِّعْرَىٰ','وَأَنَّهُ أَهْلَكَ عَادًا الْأُولَىٰ',
'وَثَمُودَ فَمَا أَبْقَىٰ','وَقَوْمَ نُوحٍ مِّن قَبْلُ إِنَّهُمْ كَانُوا هُمْ أَظْلَمَ وَأَطْغَىٰ','وَالْمُؤْتَفِكَةَ أَهْوَىٰ','فَغَشَّاهَا مَا غَشَّىٰ','فَبِأَيِّ آلَاءِ رَبِّكَ تَتَمَارَىٰ','هَٰذَا نَذِيرٌ مِّنَ النُّذُرِ الْأُولَىٰ','أَزِفَتِ الْآزِفَةُ','لَيْسَ لَهَا مِن دُونِ اللَّهِ كَاشِفَةٌ','أَفَمِنْ هَٰذَا الْحَدِيثِ تَعْجَبُونَ','وَتَضْحَكُونَ وَلَا تَبْكُونَ','وَأَنتُمْ سَامِدُونَ','فَاسْجُدُوا لِلَّهِ وَاعْبُدُوا ۩'
];
const days=[
 {name:'اليوم الأول',range:'١–٩',from:1,to:9,quote:'بدايةٌ هادئة، ونيةٌ صادقة، وقلبٌ يستعين بالله.'},{name:'اليوم الثاني',range:'١٠–١٨',from:10,to:18,quote:'كل تكرار يقرّب الآيات من قلبك أكثر.'},{name:'اليوم الثالث',range:'١٩–٣٠',from:19,to:30,quote:'ثباتك اليوم هو جمال إتقانك غدًا.'},{name:'اليوم الرابع',range:'٣١–٤٠',from:31,to:40,quote:'سعيك محفوظ عند الله؛ فأكملي بقلب مطمئن.'},{name:'اليوم الخامس',range:'٤١–٥٠',from:41,to:50,quote:'مع كل آية يزداد القلب يقينًا ونورًا.'},{name:'اليوم السادس',range:'٥١–٦٢',from:51,to:62,quote:'اقترب الوصول، فاجعلي الختام سجدة شكر.'}
];
const arabicNum=(n:number)=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[+d]);
function Page({children,n,className=''}:{children:React.ReactNode,n:number,className?:string}){return <section className={`page ${className}`}><div className="corner c1"/><div className="corner c2"/><div className="stars">✦ · ✧</div>{children}<footer><span>رحلتي مع سورة النجم</span><b>{arabicNum(n)}</b></footer></section>}
function LineInput({label,wide=false}:{label:string,wide?:boolean}){return <label className={`line-input ${wide?'wide':''}`}><span>{label}</span><input /></label>}
function Writing({title,rows=4}:{title:string,rows?:number}){return <div className="writing"><h3>{title}</h3>{Array.from({length:rows},(_,i)=><input key={i}/>)}</div>}
function Header({kicker,title,sub}:{kicker?:string,title:string,sub?:string}){return <header className="page-head">{kicker&&<span>{kicker}</span>}<h2>{title}</h2>{sub&&<p>{sub}</p>}</header>}
function Checklist(){return <div className="check-row">{['قرأت','حفظت','راجعت','أتقنت'].map(x=><label key={x}><input type="checkbox"/> <span>{x}</span></label>)}</div>}
function App(){
 const [saved,setSaved]=useState(false);
 useEffect(()=>{const data=localStorage.getItem('najm-notebook-fields');if(data){const vals=JSON.parse(data);setTimeout(()=>document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input:not([type=checkbox]),textarea').forEach((el,i)=>el.value=vals[i]||''),0)}},[]);
 const save=()=>{const vals=[...document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input:not([type=checkbox]),textarea')].map(x=>x.value);localStorage.setItem('najm-notebook-fields',JSON.stringify(vals));setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <><div className="toolbar"><div><b>رحلتي مع سورة النجم</b><small>مذكرة تفاعلية · ٢٠ صفحة A4</small></div><button onClick={save}>{saved?'تم الحفظ ✓':'حفظ إجاباتي'}</button><button className="print" onClick={()=>window.print()}>تنزيل / طباعة PDF</button></div><main>
  <Page n={1} className="cover"><div className="moon">☾<i>✦</i></div><p className="overline">مذكرة حفظ وتدبر</p><h1>رحلتي مع<br/><em>سورة النجم</em></h1><div className="gold-rule">✦</div><blockquote>«أحفظها بقلبٍ حاضر، وأتدبرها بروحٍ مطمئنة»</blockquote><div className="cover-fields"><LineInput label="الاسم"/><LineInput label="التاريخ"/><LineInput label="هدفي" wide/><p>حفظ سورة النجم بإتقان</p></div></Page>
  <Page n={2} className="welcome"><div className="petals">❀</div><p className="overline">أهلًا بكِ في رحلتك</p><h2>كل آية تحفظينها<br/>هي <em>نورٌ جديد</em> في قلبك،<br/>وخطوة أقرب إلى الله.</h2><p className="intro">خذي هذه الرحلة برفق، وكرري دون استعجال، واستحضري أن أعظم الإنجاز ما ثبت في القلب وأثمر في العمل.</p><div className="dua">اللهم افتح عليّ فتوح العارفين، وارزقني حفظ كتابك والعمل به.</div></Page>
  <Page n={3}><Header kicker="بين يدي السورة" title="تعرّفي إلى سورة النجم" sub="معرفة الطريق تجعل الرحلة أعمق وأجمل"/><div className="facts"><article><small>اسم السورة</small><b>النجم</b></article><article><small>نوعها</small><b>مكية</b></article><article><small>عدد آياتها</small><b>٦٢ آية</b></article></div><div className="info-card"><h3>سبب التسمية</h3><p>سُمّيت «سورة النجم» لافتتاحها بالقسم بالنجم في قوله تعالى: ﴿وَالنَّجْمِ إِذَا هَوَىٰ﴾.</p></div><h3 className="section-title">أهم محاور السورة</h3><div className="themes">{['صدق الوحي وثبات رسالة النبي ﷺ','توحيد الله وبطلان عبادة غيره','الحساب والجزاء وعدل الله','دلائل قدرة الله وعظمته','الاستعداد للآخرة بالسجود والعبادة'].map((x,i)=><div key={x}><i>{arabicNum(i+1)}</i><span>{x}</span></div>)}</div><div className="note">وقفة قبل البدء: أخلصي نيتك، واختاري وقتًا هادئًا ومكانًا ثابتًا للحفظ.</div></Page>
  <Page n={4}><Header kicker="سبعة أيام بصحبة النجم" title="خطة الحفظ" sub="علّمي مربع الإنجاز بعد إتمام مهمة كل يوم"/><div className="plan-table"><div className="thead"><b>اليوم</b><b>المقطع</b><b>أتممت</b></div>{[...days,{name:'اليوم السابع',range:'مراجعة السورة كاملة'}].map(d=><div key={d.name}><b>{d.name}</b><span>{'from'in d?`الآيات ${d.range}`:d.range}</span><input type="checkbox"/></div>)}</div><div className="habit"><h3>موعدي اليومي مع القرآن</h3><div><LineInput label="الوقت"/><LineInput label="المكان"/></div><p>مدة مقترحة: ٢٠–٣٠ دقيقة للحفظ، ثم ١٠ دقائق للمراجعة.</p></div><div className="soft-quote">«أحب الأعمال إلى الله أدومها وإن قل»</div></Page>
  {days.flatMap((d,idx)=>[<Page n={5+idx*2} key={`${d.name}-a`}><Header kicker={`${d.name} · الآيات ${d.range}`} title="أقرأ وأحفظ" sub={d.quote}/><div className={`quran ${d.to-d.from>10?'dense':''}`}>{verses.slice(d.from-1,d.to).map((v,i)=><span key={v}>{v} <b>﴿{arabicNum(d.from+i)}﴾</b> </span>)}</div><div className="recite"><label><input type="checkbox"/> أقرأ المقطع ٥ مرات</label><div className="five">{[1,2,3,4,5].map(x=><i key={x}>{arabicNum(x)}</i>)}</div></div><Checklist/><p className="source">نص الآيات: سورة النجم برواية حفص عن عاصم · راجعي التلاوة مع مصحف موثوق.</p></Page>,<Page n={6+idx*2} key={`${d.name}-b`}><Header kicker={`${d.name} · دفتر التثبيت`} title="أثبّت ما حفظت" sub="الكتابة والتسميع يصنعان ذاكرة أقوى"/><div className="tasmee"><label><input type="checkbox"/><b>أسمّع لنفسي</b><small>دون النظر إلى المصحف</small></label><label><input type="checkbox"/><b>أسمّع لشخص آخر</b><small>وأدوّن مواضع التردد</small></label></div><Writing title="الكلمات الصعبة" rows={5}/><Writing title="معنى اليوم الذي لمسني" rows={3}/><div className="mini-reflect"><span>وقفة قلب</span><textarea placeholder="كيف أعيش هذا المعنى اليوم؟"/></div><Checklist/></Page>])}
  <Page n={17}><Header kicker="تدبر وامتثال" title="ماذا تعلّمت من سورة النجم؟" sub="اكتبي بصدق؛ لا توجد إجابة مثالية، بل قلب يتأمل"/><div className="questions">{['ما الآية التي أثرت في قلبي؟','ماذا عرّفتني السورة عن عظمة الله؟','ما الشيء الذي أريد تغييره في نفسي؟','كيف أستعد للقاء الله بأعمال أجمل؟'].map(q=><label key={q}><b>{q}</b><textarea/></label>)}</div></Page>
  <Page n={18}><Header kicker="زاد الفهم" title="معاني كلمات مختارة" sub="معانٍ موجزة تعين على الحفظ والتدبر"/><div className="vocab"><div><b>الكلمة</b><b>المعنى الميسّر</b></div>{[['الهوى','ميل النفس ورغبتها'],['سدرة المنتهى','شجرة عظيمة في السماء السابعة'],['اللات','صنم كان يُعبد في الجاهلية'],['العزى','صنم من أصنام الجاهلية'],['اللَّمم','صغائر الذنوب وما يقع نادرًا'],['أكدى','قطع عطاءه ومنعه'],['وازرة','نفس حاملة للذنب'],['سعى','عمل واجتهد'],['المنتهى','المرجع والمصير'],['الشِّعرى','نجم لامع كان بعض العرب يعبدونه'],['المؤتفكة','قرى قوم لوط المنقلبة'],['سامدون','لاهُون معرضون متكبرون']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></Page>
  <Page n={19}><Header kicker="تثبيت وإتقان" title="مراجعتي النهائية" sub="كرري السورة كاملة في أوقات متباعدة"/><div className="review"><div className="thead"><b>المراجعة</b><b>التاريخ</b><b>مواضع تحتاج تثبيتًا</b><b>تم</b></div>{[1,2,3,4,5].map(i=><div key={i}><b>المرة {arabicNum(i)}</b><input/><input/><input type="checkbox"/></div>)}</div><h3 className="section-title">تقييمي لحفظي</h3><div className="rating">{['ممتاز','جيد جدًا','أحتاج مراجعة'].map(x=><label key={x}><input type="checkbox"/><span>{x}</span></label>)}</div><blockquote className="final-quote">«لا أبحث عن الحفظ السريع، بل عن حفظٍ ثابت يسكن قلبي.»</blockquote><LineInput label="خطوتي القادمة للمحافظة على السورة" wide/></Page>
  <Page n={20} className="certificate"><div className="seal">✦</div><p className="overline">الحمد لله الذي بنعمته تتم الصالحات</p><h2>أتممت حفظ<br/><em>سورة النجم</em><br/>بفضل الله 🤍</h2><div className="cert-box"><span>شهادة إتمام</span><p>تشهد هذه الصفحة أن</p><input aria-label="الاسم"/><p>قد أتمّت حفظ سورة النجم بتاريخ</p><input aria-label="التاريخ"/><div className="signature"><LineInput label="التوقيع"/><LineInput label="توقيع المعلّمة / المسمّعة"/></div></div><blockquote>اللهم اجعل القرآن ربيع قلبي ونور صدري.</blockquote></Page>
 </main></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
